FROM node:lts-alpine

ARG CATALOG_URL

RUN mkdir /opt/src
WORKDIR /opt/src

RUN npm install --global http-server

RUN apk add --no-cache git

RUN git clone --depth=1 \
    https://github.com/radiantearth/stac-browser \
    --branch v3.0.1

WORKDIR /opt/src/stac-browser
# COPY config_tile.js .

RUN npm install

WORKDIR /opt/src/stac-browser

CMD "npm" "start" -- --open --catalogUrl=$CATALOG_URL